name: endpoints
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.1
  jaguar_jwt: ^3.0.0
  models:
    path: ../models
  sql_templates:
    path: ../sql_templates
  uuid:
  mongo_dart:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
